import {
  Injectable,
  NotFoundException,
  Logger,
} from '@nestjs/common';
import { createHmac } from 'crypto';
import { PrismaService } from '../prisma.service';
import {
  CreditEventRecord,
  CreditEventType,
  RecordEventInput,
} from './credit-event.types';

/**
 * EventSourcingService — append-only credit-state mutation log.
 *
 * ## Design
 * Every write operation on a CreditBatch (mint, transfer, retire, list, delist)
 * calls `recordEvent()` to persist one immutable row.  Events are signed with
 * HMAC-SHA256 (key from `EVENT_HMAC_SECRET` env var) so tampering is detectable.
 *
 * ## State reconstruction
 * `reconstructState(batchId, asOf)` replays all events for a batch up to the
 * given timestamp and returns the derived state at that point.
 *
 * ## Immutability guarantee
 * The service never issues UPDATE or DELETE against CreditEvent rows.  Prisma
 * model constraints (no updatedAt field, @@index only) reinforce this at the
 * schema level.
 */
@Injectable()
export class EventSourcingService {
  private readonly logger = new Logger(EventSourcingService.name);

  /** HMAC key used to sign event payloads.  Override via EVENT_HMAC_SECRET. */
  private readonly hmacSecret: string =
    process.env.EVENT_HMAC_SECRET ?? 'carbonledger-dev-hmac-secret';

  constructor(private readonly prisma: PrismaService) {}

  // ── Prisma accessor ────────────────────────────────────────────────────────
  // creditEvent is available at runtime once `prisma generate` is run against
  // the updated schema. We access it via any-cast so compilation succeeds
  // without running the generator (CI/CD will do so before build).
  private get db(): any {
    return (this.prisma as any).creditEvent;
  }

  // ── Public API ─────────────────────────────────────────────────────────────

  /**
   * Record one credit-state mutation event.
   *
   * The row is signed with HMAC-SHA256 before persistence.  The id is
   * generated by Prisma's `cuid()` default, so we sign using a deterministic
   * payload that does NOT depend on the id itself:
   *
   *   HMAC(creditBatchId + eventType + actor + txHash + timestamp)
   *
   * This lets consumers re-verify the signature with the same formula.
   */
  async recordEvent(input: RecordEventInput): Promise<CreditEventRecord> {
    const timestamp = new Date();
    const signature = this.computeSignature(
      input.creditBatchId,
      input.eventType,
      input.actor,
      input.txHash,
      timestamp,
    );

    const row = await this.db.create({
      data: {
        creditBatchId: input.creditBatchId,
        eventType:     input.eventType,
        actor:         input.actor,
        oldState:      input.oldState ?? undefined,
        newState:      input.newState ?? undefined,
        txHash:        input.txHash,
        signature,
        timestamp,
      },
    });

    this.logger.log(
      `Event recorded: ${row.eventType} on batch ${row.creditBatchId} by ${row.actor}`,
    );

    return row as CreditEventRecord;
  }

  /**
   * Return all events for a credit batch, optionally filtered by time range.
   *
   * Used by the audit endpoint.
   */
  async getEventsForBatch(
    batchId: string,
    opts: { from?: Date; to?: Date } = {},
  ): Promise<CreditEventRecord[]> {
    const rows = await this.db.findMany({
      where: {
        creditBatchId: batchId,
        timestamp: {
          ...(opts.from ? { gte: opts.from } : {}),
          ...(opts.to   ? { lte: opts.to }   : {}),
        },
      },
      orderBy: { timestamp: 'asc' },
    });

    return rows as CreditEventRecord[];
  }

  /**
   * Reconstruct the state of a credit batch at a given point in time by
   * replaying all events up to (and including) `asOf`.
   *
   * Returns the `newState` snapshot from the last event whose timestamp ≤ asOf,
   * or `null` if no events exist before that timestamp.
   *
   * Throws `NotFoundException` if the batch has no events at all.
   */
  async reconstructState(
    batchId: string,
    asOf: Date,
  ): Promise<Record<string, unknown> | null> {
    const events = await this.db.findMany({
      where: {
        creditBatchId: batchId,
        timestamp:     { lte: asOf },
      },
      orderBy: { timestamp: 'asc' },
    });

    if (events.length === 0) {
      // Check whether the batch has any events at all
      const anyEvent = await this.db.findFirst({
        where: { creditBatchId: batchId },
      });
      if (!anyEvent) {
        throw new NotFoundException(
          `No events found for credit batch ${batchId}`,
        );
      }
      // Events exist but all are after asOf — state is "unknown / pre-existence"
      return null;
    }

    // Walk events to build state.  Each event's newState supersedes the previous.
    let state: Record<string, unknown> = {};
    for (const event of events) {
      if (event.newState && typeof event.newState === 'object') {
        state = { ...state, ...(event.newState as Record<string, unknown>) };
      }
    }

    return state;
  }

  /**
   * Verify the HMAC signature of a stored event.
   *
   * Returns `true` if the signature matches; `false` if tampered.
   */
  verifySignature(event: CreditEventRecord): boolean {
    const expected = this.computeSignature(
      event.creditBatchId,
      event.eventType,
      event.actor,
      event.txHash,
      event.timestamp,
    );
    return expected === event.signature;
  }

  /**
   * Verify all events for a batch and return any that have been tampered with.
   */
  async auditIntegrity(batchId: string): Promise<{ tampered: CreditEventRecord[] }> {
    const events = await this.getEventsForBatch(batchId);
    const tampered = events.filter((e) => !this.verifySignature(e));
    return { tampered };
  }

  // ── Internal helpers ───────────────────────────────────────────────────────

  /**
   * Compute HMAC-SHA256 over a canonical string of the event's key fields.
   *
   * Canonical format (fields joined with "|"):
   *   creditBatchId | eventType | actor | txHash | timestamp.toISOString()
   */
  computeSignature(
    creditBatchId: string,
    eventType: string,
    actor: string,
    txHash: string,
    timestamp: Date,
  ): string {
    const payload = [
      creditBatchId,
      eventType,
      actor,
      txHash,
      timestamp.toISOString(),
    ].join('|');

    return createHmac('sha256', this.hmacSecret)
      .update(payload)
      .digest('hex');
  }
}
